/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC3643,
  IERC3643Interface,
} from "../../../contracts/InvestmentController.sol/IERC3643";

const _abi = [
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "issue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC3643__factory {
  static readonly abi = _abi;
  static createInterface(): IERC3643Interface {
    return new Interface(_abi) as IERC3643Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): IERC3643 {
    return new Contract(address, _abi, runner) as unknown as IERC3643;
  }
}
