/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as chainXInvestmentControllerSol from "./ChainXInvestmentController.sol";
export * as simpleIdentitySol from "./SimpleIdentity.sol";
export { DeployableClaimTopicsRegistry__factory } from "./DeployableClaimTopicsRegistry__factory";
export { DeployableIdentityRegistry__factory } from "./DeployableIdentityRegistry__factory";
export { DeployableIdentityRegistryStorage__factory } from "./DeployableIdentityRegistryStorage__factory";
export { DeployableModularCompliance__factory } from "./DeployableModularCompliance__factory";
export { DeployableToken__factory } from "./DeployableToken__factory";
export { DeployableTrustedIssuersRegistry__factory } from "./DeployableTrustedIssuersRegistry__factory";
