/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ClaimTopicsRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addClaimTopic"
      | "getClaimTopics"
      | "isClaimTopic"
      | "owner"
      | "removeClaimTopic"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ClaimTopicAdded"
      | "ClaimTopicRemoved"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addClaimTopic",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimTopics",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isClaimTopic",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeClaimTopic",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addClaimTopic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimTopics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isClaimTopic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeClaimTopic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ClaimTopicAddedEvent {
  export type InputTuple = [topic: BigNumberish];
  export type OutputTuple = [topic: bigint];
  export interface OutputObject {
    topic: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimTopicRemovedEvent {
  export type InputTuple = [topic: BigNumberish];
  export type OutputTuple = [topic: bigint];
  export interface OutputObject {
    topic: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ClaimTopicsRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ClaimTopicsRegistry;
  waitForDeployment(): Promise<this>;

  interface: ClaimTopicsRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addClaimTopic: TypedContractMethod<
    [_topic: BigNumberish],
    [void],
    "nonpayable"
  >;

  getClaimTopics: TypedContractMethod<[], [bigint[]], "view">;

  isClaimTopic: TypedContractMethod<[_topic: BigNumberish], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeClaimTopic: TypedContractMethod<
    [_topic: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addClaimTopic"
  ): TypedContractMethod<[_topic: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getClaimTopics"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "isClaimTopic"
  ): TypedContractMethod<[_topic: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeClaimTopic"
  ): TypedContractMethod<[_topic: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ClaimTopicAdded"
  ): TypedContractEvent<
    ClaimTopicAddedEvent.InputTuple,
    ClaimTopicAddedEvent.OutputTuple,
    ClaimTopicAddedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimTopicRemoved"
  ): TypedContractEvent<
    ClaimTopicRemovedEvent.InputTuple,
    ClaimTopicRemovedEvent.OutputTuple,
    ClaimTopicRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "ClaimTopicAdded(uint256)": TypedContractEvent<
      ClaimTopicAddedEvent.InputTuple,
      ClaimTopicAddedEvent.OutputTuple,
      ClaimTopicAddedEvent.OutputObject
    >;
    ClaimTopicAdded: TypedContractEvent<
      ClaimTopicAddedEvent.InputTuple,
      ClaimTopicAddedEvent.OutputTuple,
      ClaimTopicAddedEvent.OutputObject
    >;

    "ClaimTopicRemoved(uint256)": TypedContractEvent<
      ClaimTopicRemovedEvent.InputTuple,
      ClaimTopicRemovedEvent.OutputTuple,
      ClaimTopicRemovedEvent.OutputObject
    >;
    ClaimTopicRemoved: TypedContractEvent<
      ClaimTopicRemovedEvent.InputTuple,
      ClaimTopicRemovedEvent.OutputTuple,
      ClaimTopicRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
