/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as chainXInvestmentControllerSol from "./ChainXInvestmentController.sol";
export type { chainXInvestmentControllerSol };
import type * as simpleIdentitySol from "./SimpleIdentity.sol";
export type { simpleIdentitySol };
export type { DeployableClaimTopicsRegistry } from "./DeployableClaimTopicsRegistry";
export type { DeployableIdentityRegistry } from "./DeployableIdentityRegistry";
export type { DeployableIdentityRegistryStorage } from "./DeployableIdentityRegistryStorage";
export type { DeployableModularCompliance } from "./DeployableModularCompliance";
export type { DeployableToken } from "./DeployableToken";
export type { DeployableTrustedIssuersRegistry } from "./DeployableTrustedIssuersRegistry";
