/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PayoutDistributorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimMultiplePayouts"
      | "claimPayout"
      | "getClaimableAmount"
      | "getPayoutInfo"
      | "getTotalUnclaimed"
      | "hasClaimed"
      | "owner"
      | "payoutCount"
      | "payouts"
      | "renounceOwnership"
      | "schedulePayout"
      | "securityToken"
      | "stablecoin"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PayoutClaimed"
      | "PayoutScheduled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimMultiplePayouts",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimPayout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimableAmount",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayoutInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalUnclaimed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimed",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payoutCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "payouts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "schedulePayout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "securityToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stablecoin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimMultiplePayouts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimPayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPayoutInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalUnclaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasClaimed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payoutCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payouts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "schedulePayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "securityToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stablecoin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutClaimedEvent {
  export type InputTuple = [
    payoutId: BigNumberish,
    investor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    payoutId: bigint,
    investor: string,
    amount: bigint
  ];
  export interface OutputObject {
    payoutId: bigint;
    investor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutScheduledEvent {
  export type InputTuple = [
    payoutId: BigNumberish,
    amount: BigNumberish,
    supply: BigNumberish
  ];
  export type OutputTuple = [payoutId: bigint, amount: bigint, supply: bigint];
  export interface OutputObject {
    payoutId: bigint;
    amount: bigint;
    supply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PayoutDistributor extends BaseContract {
  connect(runner?: ContractRunner | null): PayoutDistributor;
  waitForDeployment(): Promise<this>;

  interface: PayoutDistributorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimMultiplePayouts: TypedContractMethod<
    [_payoutIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  claimPayout: TypedContractMethod<
    [_payoutId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getClaimableAmount: TypedContractMethod<
    [_investor: AddressLike, _payoutId: BigNumberish],
    [bigint],
    "view"
  >;

  getPayoutInfo: TypedContractMethod<
    [_payoutId: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        totalAmount: bigint;
        snapshotSupply: bigint;
        timestamp: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;

  getTotalUnclaimed: TypedContractMethod<
    [_investor: AddressLike],
    [bigint],
    "view"
  >;

  hasClaimed: TypedContractMethod<
    [_investor: AddressLike, _payoutId: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  payoutCount: TypedContractMethod<[], [bigint], "view">;

  payouts: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        totalAmount: bigint;
        snapshotSupply: bigint;
        timestamp: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  schedulePayout: TypedContractMethod<
    [_amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  securityToken: TypedContractMethod<[], [string], "view">;

  stablecoin: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimMultiplePayouts"
  ): TypedContractMethod<[_payoutIds: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimPayout"
  ): TypedContractMethod<[_payoutId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getClaimableAmount"
  ): TypedContractMethod<
    [_investor: AddressLike, _payoutId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPayoutInfo"
  ): TypedContractMethod<
    [_payoutId: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        totalAmount: bigint;
        snapshotSupply: bigint;
        timestamp: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalUnclaimed"
  ): TypedContractMethod<[_investor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasClaimed"
  ): TypedContractMethod<
    [_investor: AddressLike, _payoutId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payoutCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "payouts"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        totalAmount: bigint;
        snapshotSupply: bigint;
        timestamp: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "schedulePayout"
  ): TypedContractMethod<[_amount: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "securityToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "stablecoin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PayoutClaimed"
  ): TypedContractEvent<
    PayoutClaimedEvent.InputTuple,
    PayoutClaimedEvent.OutputTuple,
    PayoutClaimedEvent.OutputObject
  >;
  getEvent(
    key: "PayoutScheduled"
  ): TypedContractEvent<
    PayoutScheduledEvent.InputTuple,
    PayoutScheduledEvent.OutputTuple,
    PayoutScheduledEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PayoutClaimed(uint256,address,uint256)": TypedContractEvent<
      PayoutClaimedEvent.InputTuple,
      PayoutClaimedEvent.OutputTuple,
      PayoutClaimedEvent.OutputObject
    >;
    PayoutClaimed: TypedContractEvent<
      PayoutClaimedEvent.InputTuple,
      PayoutClaimedEvent.OutputTuple,
      PayoutClaimedEvent.OutputObject
    >;

    "PayoutScheduled(uint256,uint256,uint256)": TypedContractEvent<
      PayoutScheduledEvent.InputTuple,
      PayoutScheduledEvent.OutputTuple,
      PayoutScheduledEvent.OutputObject
    >;
    PayoutScheduled: TypedContractEvent<
      PayoutScheduledEvent.InputTuple,
      PayoutScheduledEvent.OutputTuple,
      PayoutScheduledEvent.OutputObject
    >;
  };
}
