/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ProjectRegistry {
  export type ProjectStruct = {
    name: string;
    securityToken: AddressLike;
    investmentController: AddressLike;
    pricePerToken: BigNumberish;
    maxCap: BigNumberish;
    stablecoin: AddressLike;
    metadataURI: string;
    active: boolean;
    createdAt: BigNumberish;
  };

  export type ProjectStructOutput = [
    name: string,
    securityToken: string,
    investmentController: string,
    pricePerToken: bigint,
    maxCap: bigint,
    stablecoin: string,
    metadataURI: string,
    active: boolean,
    createdAt: bigint
  ] & {
    name: string;
    securityToken: string;
    investmentController: string;
    pricePerToken: bigint;
    maxCap: bigint;
    stablecoin: string;
    metadataURI: string;
    active: boolean;
    createdAt: bigint;
  };
}

export interface ProjectRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deactivateProject"
      | "getActiveProjects"
      | "getAllProjects"
      | "getProject"
      | "getProjectByToken"
      | "getProjectCount"
      | "owner"
      | "registerProject"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateProject"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ProjectCreated"
      | "ProjectDeactivated"
      | "ProjectUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deactivateProject",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveProjects",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllProjects",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProject",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectByToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerProject",
    values: [
      string,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProject",
    values: [BigNumberish, BigNumberish, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "deactivateProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveProjects",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllProjects",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProject", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProjectByToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProject",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectCreatedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    name: string,
    securityToken: AddressLike,
    investmentController: AddressLike
  ];
  export type OutputTuple = [
    projectId: bigint,
    name: string,
    securityToken: string,
    investmentController: string
  ];
  export interface OutputObject {
    projectId: bigint;
    name: string;
    securityToken: string;
    investmentController: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectDeactivatedEvent {
  export type InputTuple = [projectId: BigNumberish];
  export type OutputTuple = [projectId: bigint];
  export interface OutputObject {
    projectId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectUpdatedEvent {
  export type InputTuple = [projectId: BigNumberish];
  export type OutputTuple = [projectId: bigint];
  export interface OutputObject {
    projectId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProjectRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ProjectRegistry;
  waitForDeployment(): Promise<this>;

  interface: ProjectRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deactivateProject: TypedContractMethod<
    [_projectId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getActiveProjects: TypedContractMethod<
    [],
    [ProjectRegistry.ProjectStructOutput[]],
    "view"
  >;

  getAllProjects: TypedContractMethod<
    [],
    [ProjectRegistry.ProjectStructOutput[]],
    "view"
  >;

  getProject: TypedContractMethod<
    [_projectId: BigNumberish],
    [ProjectRegistry.ProjectStructOutput],
    "view"
  >;

  getProjectByToken: TypedContractMethod<
    [_token: AddressLike],
    [bigint],
    "view"
  >;

  getProjectCount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerProject: TypedContractMethod<
    [
      _name: string,
      _securityToken: AddressLike,
      _investmentController: AddressLike,
      _pricePerToken: BigNumberish,
      _maxCap: BigNumberish,
      _stablecoin: AddressLike,
      _metadataURI: string
    ],
    [bigint],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateProject: TypedContractMethod<
    [
      _projectId: BigNumberish,
      _pricePerToken: BigNumberish,
      _maxCap: BigNumberish,
      _metadataURI: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deactivateProject"
  ): TypedContractMethod<[_projectId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveProjects"
  ): TypedContractMethod<[], [ProjectRegistry.ProjectStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getAllProjects"
  ): TypedContractMethod<[], [ProjectRegistry.ProjectStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getProject"
  ): TypedContractMethod<
    [_projectId: BigNumberish],
    [ProjectRegistry.ProjectStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProjectByToken"
  ): TypedContractMethod<[_token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProjectCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerProject"
  ): TypedContractMethod<
    [
      _name: string,
      _securityToken: AddressLike,
      _investmentController: AddressLike,
      _pricePerToken: BigNumberish,
      _maxCap: BigNumberish,
      _stablecoin: AddressLike,
      _metadataURI: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateProject"
  ): TypedContractMethod<
    [
      _projectId: BigNumberish,
      _pricePerToken: BigNumberish,
      _maxCap: BigNumberish,
      _metadataURI: string
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProjectCreated"
  ): TypedContractEvent<
    ProjectCreatedEvent.InputTuple,
    ProjectCreatedEvent.OutputTuple,
    ProjectCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectDeactivated"
  ): TypedContractEvent<
    ProjectDeactivatedEvent.InputTuple,
    ProjectDeactivatedEvent.OutputTuple,
    ProjectDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectUpdated"
  ): TypedContractEvent<
    ProjectUpdatedEvent.InputTuple,
    ProjectUpdatedEvent.OutputTuple,
    ProjectUpdatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProjectCreated(uint256,string,address,address)": TypedContractEvent<
      ProjectCreatedEvent.InputTuple,
      ProjectCreatedEvent.OutputTuple,
      ProjectCreatedEvent.OutputObject
    >;
    ProjectCreated: TypedContractEvent<
      ProjectCreatedEvent.InputTuple,
      ProjectCreatedEvent.OutputTuple,
      ProjectCreatedEvent.OutputObject
    >;

    "ProjectDeactivated(uint256)": TypedContractEvent<
      ProjectDeactivatedEvent.InputTuple,
      ProjectDeactivatedEvent.OutputTuple,
      ProjectDeactivatedEvent.OutputObject
    >;
    ProjectDeactivated: TypedContractEvent<
      ProjectDeactivatedEvent.InputTuple,
      ProjectDeactivatedEvent.OutputTuple,
      ProjectDeactivatedEvent.OutputObject
    >;

    "ProjectUpdated(uint256)": TypedContractEvent<
      ProjectUpdatedEvent.InputTuple,
      ProjectUpdatedEvent.OutputTuple,
      ProjectUpdatedEvent.OutputObject
    >;
    ProjectUpdated: TypedContractEvent<
      ProjectUpdatedEvent.InputTuple,
      ProjectUpdatedEvent.OutputTuple,
      ProjectUpdatedEvent.OutputObject
    >;
  };
}
