/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IProjectRegistry,
  IProjectRegistryInterface,
} from "../../../contracts/ProjectTokenFactory.sol/IProjectRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_name",
        type: "string",
      },
      {
        internalType: "address",
        name: "_securityToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "_investmentController",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_pricePerToken",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_maxCap",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_stablecoin",
        type: "address",
      },
      {
        internalType: "string",
        name: "_metadataURI",
        type: "string",
      },
    ],
    name: "registerProject",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IProjectRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IProjectRegistryInterface {
    return new Interface(_abi) as IProjectRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IProjectRegistry {
    return new Contract(address, _abi, runner) as unknown as IProjectRegistry;
  }
}
