/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IdentityRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimTopicsRegistry"
      | "contains"
      | "deleteIdentity"
      | "getInvestors"
      | "identity"
      | "identityStorage"
      | "investorCountry"
      | "isVerified"
      | "owner"
      | "registerIdentity"
      | "renounceOwnership"
      | "transferOwnership"
      | "trustedIssuersRegistry"
      | "updateCountry"
      | "updateIdentity"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "IdentityRegistered"
      | "IdentityRemoved"
      | "IdentityUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimTopicsRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contains",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteIdentity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getInvestors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "identity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identityStorage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "investorCountry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerIdentity",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedIssuersRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateCountry",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateIdentity",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimTopicsRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contains", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deleteIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInvestors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "identity", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "identityStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "investorCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedIssuersRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateIdentity",
    data: BytesLike
  ): Result;
}

export namespace IdentityRegisteredEvent {
  export type InputTuple = [investor: AddressLike, identity: AddressLike];
  export type OutputTuple = [investor: string, identity: string];
  export interface OutputObject {
    investor: string;
    identity: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityRemovedEvent {
  export type InputTuple = [investor: AddressLike];
  export type OutputTuple = [investor: string];
  export interface OutputObject {
    investor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityUpdatedEvent {
  export type InputTuple = [
    investor: AddressLike,
    oldIdentity: AddressLike,
    newIdentity: AddressLike
  ];
  export type OutputTuple = [
    investor: string,
    oldIdentity: string,
    newIdentity: string
  ];
  export interface OutputObject {
    investor: string;
    oldIdentity: string;
    newIdentity: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IdentityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IdentityRegistry;
  waitForDeployment(): Promise<this>;

  interface: IdentityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimTopicsRegistry: TypedContractMethod<[], [string], "view">;

  contains: TypedContractMethod<[_investor: AddressLike], [boolean], "view">;

  deleteIdentity: TypedContractMethod<
    [_investor: AddressLike],
    [void],
    "nonpayable"
  >;

  getInvestors: TypedContractMethod<[], [string[]], "view">;

  identity: TypedContractMethod<[_investor: AddressLike], [string], "view">;

  identityStorage: TypedContractMethod<[], [string], "view">;

  investorCountry: TypedContractMethod<
    [_investor: AddressLike],
    [bigint],
    "view"
  >;

  isVerified: TypedContractMethod<[_investor: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerIdentity: TypedContractMethod<
    [_investor: AddressLike, _identity: AddressLike, _country: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  trustedIssuersRegistry: TypedContractMethod<[], [string], "view">;

  updateCountry: TypedContractMethod<
    [_investor: AddressLike, _country: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateIdentity: TypedContractMethod<
    [_investor: AddressLike, _identity: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimTopicsRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "contains"
  ): TypedContractMethod<[_investor: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "deleteIdentity"
  ): TypedContractMethod<[_investor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getInvestors"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "identity"
  ): TypedContractMethod<[_investor: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "identityStorage"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "investorCountry"
  ): TypedContractMethod<[_investor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<[_investor: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerIdentity"
  ): TypedContractMethod<
    [_investor: AddressLike, _identity: AddressLike, _country: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trustedIssuersRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateCountry"
  ): TypedContractMethod<
    [_investor: AddressLike, _country: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateIdentity"
  ): TypedContractMethod<
    [_investor: AddressLike, _identity: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "IdentityRegistered"
  ): TypedContractEvent<
    IdentityRegisteredEvent.InputTuple,
    IdentityRegisteredEvent.OutputTuple,
    IdentityRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "IdentityRemoved"
  ): TypedContractEvent<
    IdentityRemovedEvent.InputTuple,
    IdentityRemovedEvent.OutputTuple,
    IdentityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "IdentityUpdated"
  ): TypedContractEvent<
    IdentityUpdatedEvent.InputTuple,
    IdentityUpdatedEvent.OutputTuple,
    IdentityUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "IdentityRegistered(address,address)": TypedContractEvent<
      IdentityRegisteredEvent.InputTuple,
      IdentityRegisteredEvent.OutputTuple,
      IdentityRegisteredEvent.OutputObject
    >;
    IdentityRegistered: TypedContractEvent<
      IdentityRegisteredEvent.InputTuple,
      IdentityRegisteredEvent.OutputTuple,
      IdentityRegisteredEvent.OutputObject
    >;

    "IdentityRemoved(address)": TypedContractEvent<
      IdentityRemovedEvent.InputTuple,
      IdentityRemovedEvent.OutputTuple,
      IdentityRemovedEvent.OutputObject
    >;
    IdentityRemoved: TypedContractEvent<
      IdentityRemovedEvent.InputTuple,
      IdentityRemovedEvent.OutputTuple,
      IdentityRemovedEvent.OutputObject
    >;

    "IdentityUpdated(address,address,address)": TypedContractEvent<
      IdentityUpdatedEvent.InputTuple,
      IdentityUpdatedEvent.OutputTuple,
      IdentityUpdatedEvent.OutputObject
    >;
    IdentityUpdated: TypedContractEvent<
      IdentityUpdatedEvent.InputTuple,
      IdentityUpdatedEvent.OutputTuple,
      IdentityUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
