/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as compliance from "./compliance";
export type { compliance };
import type * as registry from "./registry";
export type { registry };
import type * as storage from "./storage";
export type { storage };
export type { IIdentity } from "./IIdentity";
export type { IdentityRegistry } from "./IdentityRegistry";
export type { SecurityToken } from "./SecurityToken";
