/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ComplianceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowCountry"
      | "blockCountry"
      | "canTransfer"
      | "getLockup"
      | "isCountryAllowed"
      | "isLocked"
      | "maxHoldingAmount"
      | "minHoldingAmount"
      | "owner"
      | "renounceOwnership"
      | "setLockup"
      | "setMaxHolding"
      | "setMinHolding"
      | "setTransfersEnabled"
      | "transferOwnership"
      | "transfersEnabled"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CountryAllowed"
      | "CountryBlocked"
      | "LockupSet"
      | "MaxHoldingSet"
      | "MinHoldingSet"
      | "OwnershipTransferred"
      | "TransfersToggled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allowCountry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "blockCountry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canTransfer",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getLockup",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCountryAllowed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isLocked",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxHoldingAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minHoldingAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLockup",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxHolding",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinHolding",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTransfersEnabled",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transfersEnabled",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "allowCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blockCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLockup", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCountryAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isLocked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxHoldingAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minHoldingAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setLockup", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaxHolding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinHolding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTransfersEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transfersEnabled",
    data: BytesLike
  ): Result;
}

export namespace CountryAllowedEvent {
  export type InputTuple = [country: BigNumberish];
  export type OutputTuple = [country: bigint];
  export interface OutputObject {
    country: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CountryBlockedEvent {
  export type InputTuple = [country: BigNumberish];
  export type OutputTuple = [country: bigint];
  export interface OutputObject {
    country: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LockupSetEvent {
  export type InputTuple = [investor: AddressLike, until: BigNumberish];
  export type OutputTuple = [investor: string, until: bigint];
  export interface OutputObject {
    investor: string;
    until: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxHoldingSetEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinHoldingSetEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransfersToggledEvent {
  export type InputTuple = [enabled: boolean];
  export type OutputTuple = [enabled: boolean];
  export interface OutputObject {
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Compliance extends BaseContract {
  connect(runner?: ContractRunner | null): Compliance;
  waitForDeployment(): Promise<this>;

  interface: ComplianceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowCountry: TypedContractMethod<
    [_country: BigNumberish],
    [void],
    "nonpayable"
  >;

  blockCountry: TypedContractMethod<
    [_country: BigNumberish],
    [void],
    "nonpayable"
  >;

  canTransfer: TypedContractMethod<
    [
      _from: AddressLike,
      _to: AddressLike,
      _value: BigNumberish,
      _fromCountry: BigNumberish,
      _toCountry: BigNumberish,
      _toBalance: BigNumberish
    ],
    [boolean],
    "view"
  >;

  getLockup: TypedContractMethod<[_investor: AddressLike], [bigint], "view">;

  isCountryAllowed: TypedContractMethod<
    [_country: BigNumberish],
    [boolean],
    "view"
  >;

  isLocked: TypedContractMethod<[_investor: AddressLike], [boolean], "view">;

  maxHoldingAmount: TypedContractMethod<[], [bigint], "view">;

  minHoldingAmount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setLockup: TypedContractMethod<
    [_investor: AddressLike, _until: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxHolding: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinHolding: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTransfersEnabled: TypedContractMethod<
    [_enabled: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  transfersEnabled: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowCountry"
  ): TypedContractMethod<[_country: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "blockCountry"
  ): TypedContractMethod<[_country: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "canTransfer"
  ): TypedContractMethod<
    [
      _from: AddressLike,
      _to: AddressLike,
      _value: BigNumberish,
      _fromCountry: BigNumberish,
      _toCountry: BigNumberish,
      _toBalance: BigNumberish
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLockup"
  ): TypedContractMethod<[_investor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isCountryAllowed"
  ): TypedContractMethod<[_country: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isLocked"
  ): TypedContractMethod<[_investor: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "maxHoldingAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minHoldingAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLockup"
  ): TypedContractMethod<
    [_investor: AddressLike, _until: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxHolding"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinHolding"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTransfersEnabled"
  ): TypedContractMethod<[_enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transfersEnabled"
  ): TypedContractMethod<[], [boolean], "view">;

  getEvent(
    key: "CountryAllowed"
  ): TypedContractEvent<
    CountryAllowedEvent.InputTuple,
    CountryAllowedEvent.OutputTuple,
    CountryAllowedEvent.OutputObject
  >;
  getEvent(
    key: "CountryBlocked"
  ): TypedContractEvent<
    CountryBlockedEvent.InputTuple,
    CountryBlockedEvent.OutputTuple,
    CountryBlockedEvent.OutputObject
  >;
  getEvent(
    key: "LockupSet"
  ): TypedContractEvent<
    LockupSetEvent.InputTuple,
    LockupSetEvent.OutputTuple,
    LockupSetEvent.OutputObject
  >;
  getEvent(
    key: "MaxHoldingSet"
  ): TypedContractEvent<
    MaxHoldingSetEvent.InputTuple,
    MaxHoldingSetEvent.OutputTuple,
    MaxHoldingSetEvent.OutputObject
  >;
  getEvent(
    key: "MinHoldingSet"
  ): TypedContractEvent<
    MinHoldingSetEvent.InputTuple,
    MinHoldingSetEvent.OutputTuple,
    MinHoldingSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TransfersToggled"
  ): TypedContractEvent<
    TransfersToggledEvent.InputTuple,
    TransfersToggledEvent.OutputTuple,
    TransfersToggledEvent.OutputObject
  >;

  filters: {
    "CountryAllowed(uint16)": TypedContractEvent<
      CountryAllowedEvent.InputTuple,
      CountryAllowedEvent.OutputTuple,
      CountryAllowedEvent.OutputObject
    >;
    CountryAllowed: TypedContractEvent<
      CountryAllowedEvent.InputTuple,
      CountryAllowedEvent.OutputTuple,
      CountryAllowedEvent.OutputObject
    >;

    "CountryBlocked(uint16)": TypedContractEvent<
      CountryBlockedEvent.InputTuple,
      CountryBlockedEvent.OutputTuple,
      CountryBlockedEvent.OutputObject
    >;
    CountryBlocked: TypedContractEvent<
      CountryBlockedEvent.InputTuple,
      CountryBlockedEvent.OutputTuple,
      CountryBlockedEvent.OutputObject
    >;

    "LockupSet(address,uint256)": TypedContractEvent<
      LockupSetEvent.InputTuple,
      LockupSetEvent.OutputTuple,
      LockupSetEvent.OutputObject
    >;
    LockupSet: TypedContractEvent<
      LockupSetEvent.InputTuple,
      LockupSetEvent.OutputTuple,
      LockupSetEvent.OutputObject
    >;

    "MaxHoldingSet(uint256)": TypedContractEvent<
      MaxHoldingSetEvent.InputTuple,
      MaxHoldingSetEvent.OutputTuple,
      MaxHoldingSetEvent.OutputObject
    >;
    MaxHoldingSet: TypedContractEvent<
      MaxHoldingSetEvent.InputTuple,
      MaxHoldingSetEvent.OutputTuple,
      MaxHoldingSetEvent.OutputObject
    >;

    "MinHoldingSet(uint256)": TypedContractEvent<
      MinHoldingSetEvent.InputTuple,
      MinHoldingSetEvent.OutputTuple,
      MinHoldingSetEvent.OutputObject
    >;
    MinHoldingSet: TypedContractEvent<
      MinHoldingSetEvent.InputTuple,
      MinHoldingSetEvent.OutputTuple,
      MinHoldingSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TransfersToggled(bool)": TypedContractEvent<
      TransfersToggledEvent.InputTuple,
      TransfersToggledEvent.OutputTuple,
      TransfersToggledEvent.OutputObject
    >;
    TransfersToggled: TypedContractEvent<
      TransfersToggledEvent.InputTuple,
      TransfersToggledEvent.OutputTuple,
      TransfersToggledEvent.OutputObject
    >;
  };
}
