/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IdentityRegistryStorageInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addIdentity"
      | "country"
      | "getInvestors"
      | "identity"
      | "owner"
      | "removeIdentity"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateCountry"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CountryUpdated"
      | "IdentityRemoved"
      | "IdentityStored"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addIdentity",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "country",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getInvestors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "identity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeIdentity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCountry",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "country", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getInvestors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "identity", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCountry",
    data: BytesLike
  ): Result;
}

export namespace CountryUpdatedEvent {
  export type InputTuple = [investor: AddressLike, country: BigNumberish];
  export type OutputTuple = [investor: string, country: bigint];
  export interface OutputObject {
    investor: string;
    country: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityRemovedEvent {
  export type InputTuple = [investor: AddressLike, identity: AddressLike];
  export type OutputTuple = [investor: string, identity: string];
  export interface OutputObject {
    investor: string;
    identity: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityStoredEvent {
  export type InputTuple = [investor: AddressLike, identity: AddressLike];
  export type OutputTuple = [investor: string, identity: string];
  export interface OutputObject {
    investor: string;
    identity: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IdentityRegistryStorage extends BaseContract {
  connect(runner?: ContractRunner | null): IdentityRegistryStorage;
  waitForDeployment(): Promise<this>;

  interface: IdentityRegistryStorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addIdentity: TypedContractMethod<
    [_investor: AddressLike, _identity: AddressLike, _country: BigNumberish],
    [void],
    "nonpayable"
  >;

  country: TypedContractMethod<[_investor: AddressLike], [bigint], "view">;

  getInvestors: TypedContractMethod<[], [string[]], "view">;

  identity: TypedContractMethod<[_investor: AddressLike], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeIdentity: TypedContractMethod<
    [_investor: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateCountry: TypedContractMethod<
    [_investor: AddressLike, _country: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addIdentity"
  ): TypedContractMethod<
    [_investor: AddressLike, _identity: AddressLike, _country: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "country"
  ): TypedContractMethod<[_investor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getInvestors"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "identity"
  ): TypedContractMethod<[_investor: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeIdentity"
  ): TypedContractMethod<[_investor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateCountry"
  ): TypedContractMethod<
    [_investor: AddressLike, _country: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CountryUpdated"
  ): TypedContractEvent<
    CountryUpdatedEvent.InputTuple,
    CountryUpdatedEvent.OutputTuple,
    CountryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "IdentityRemoved"
  ): TypedContractEvent<
    IdentityRemovedEvent.InputTuple,
    IdentityRemovedEvent.OutputTuple,
    IdentityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "IdentityStored"
  ): TypedContractEvent<
    IdentityStoredEvent.InputTuple,
    IdentityStoredEvent.OutputTuple,
    IdentityStoredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "CountryUpdated(address,uint16)": TypedContractEvent<
      CountryUpdatedEvent.InputTuple,
      CountryUpdatedEvent.OutputTuple,
      CountryUpdatedEvent.OutputObject
    >;
    CountryUpdated: TypedContractEvent<
      CountryUpdatedEvent.InputTuple,
      CountryUpdatedEvent.OutputTuple,
      CountryUpdatedEvent.OutputObject
    >;

    "IdentityRemoved(address,address)": TypedContractEvent<
      IdentityRemovedEvent.InputTuple,
      IdentityRemovedEvent.OutputTuple,
      IdentityRemovedEvent.OutputObject
    >;
    IdentityRemoved: TypedContractEvent<
      IdentityRemovedEvent.InputTuple,
      IdentityRemovedEvent.OutputTuple,
      IdentityRemovedEvent.OutputObject
    >;

    "IdentityStored(address,address)": TypedContractEvent<
      IdentityStoredEvent.InputTuple,
      IdentityStoredEvent.OutputTuple,
      IdentityStoredEvent.OutputObject
    >;
    IdentityStored: TypedContractEvent<
      IdentityStoredEvent.InputTuple,
      IdentityStoredEvent.OutputTuple,
      IdentityStoredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
