/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface InvestmentControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "eurUsd"
      | "hardCap"
      | "invest"
      | "issued"
      | "maxSlippageBps"
      | "priceEuroCents"
      | "quoteUSDC"
      | "setMaxSlippageBps"
      | "token3643"
      | "treasury"
      | "usdc"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Invested"): EventFragment;

  encodeFunctionData(functionFragment: "eurUsd", values?: undefined): string;
  encodeFunctionData(functionFragment: "hardCap", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "invest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "issued", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maxSlippageBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "priceEuroCents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "quoteUSDC",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxSlippageBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token3643", values?: undefined): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(functionFragment: "eurUsd", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hardCap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "invest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "issued", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxSlippageBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceEuroCents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "quoteUSDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaxSlippageBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token3643", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace InvestedEvent {
  export type InputTuple = [
    investor: AddressLike,
    tokenAmount: BigNumberish,
    paidUSDC: BigNumberish
  ];
  export type OutputTuple = [
    investor: string,
    tokenAmount: bigint,
    paidUSDC: bigint
  ];
  export interface OutputObject {
    investor: string;
    tokenAmount: bigint;
    paidUSDC: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InvestmentController extends BaseContract {
  connect(runner?: ContractRunner | null): InvestmentController;
  waitForDeployment(): Promise<this>;

  interface: InvestmentControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  eurUsd: TypedContractMethod<[], [string], "view">;

  hardCap: TypedContractMethod<[], [bigint], "view">;

  invest: TypedContractMethod<
    [tokenAmount: BigNumberish, maxUsdcExpected: BigNumberish],
    [void],
    "nonpayable"
  >;

  issued: TypedContractMethod<[], [bigint], "view">;

  maxSlippageBps: TypedContractMethod<[], [bigint], "view">;

  priceEuroCents: TypedContractMethod<[], [bigint], "view">;

  quoteUSDC: TypedContractMethod<[tokenAmount: BigNumberish], [bigint], "view">;

  setMaxSlippageBps: TypedContractMethod<
    [bps: BigNumberish],
    [void],
    "nonpayable"
  >;

  token3643: TypedContractMethod<[], [string], "view">;

  treasury: TypedContractMethod<[], [string], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "eurUsd"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hardCap"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "invest"
  ): TypedContractMethod<
    [tokenAmount: BigNumberish, maxUsdcExpected: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "issued"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxSlippageBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "priceEuroCents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "quoteUSDC"
  ): TypedContractMethod<[tokenAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "setMaxSlippageBps"
  ): TypedContractMethod<[bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "token3643"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Invested"
  ): TypedContractEvent<
    InvestedEvent.InputTuple,
    InvestedEvent.OutputTuple,
    InvestedEvent.OutputObject
  >;

  filters: {
    "Invested(address,uint256,uint256)": TypedContractEvent<
      InvestedEvent.InputTuple,
      InvestedEvent.OutputTuple,
      InvestedEvent.OutputObject
    >;
    Invested: TypedContractEvent<
      InvestedEvent.InputTuple,
      InvestedEvent.OutputTuple,
      InvestedEvent.OutputObject
    >;
  };
}
